# Generated by Django 5.0.6 on 2024-09-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_thesis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='created_at',
            new_name='upload_date',
        ),
    ]
