# Generated by Django 5.0.6 on 2024-09-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_created_at_thesis_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
