# Generated by Django 5.0.6 on 2024-09-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_thesis_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='pdf_file',
            field=models.FileField(max_length=256, upload_to='thesis_pdf'),
        ),
    ]
