# Generated by Django 5.0.6 on 2024-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_thesis_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
